# Generated by Django 3.2 on 2024-02-24 10:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table1',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '"dashboard_table1"',
            },
        ),
        migrations.CreateModel(
            name='Table2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=255, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.table1')),
            ],
            options={
                'db_table': '"dashboard_table2"',
            },
        ),
    ]
